// <auto-generated />
namespace License.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modelPropertychanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modelPropertychanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201706190931449_modelPropertychanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
